server {
    listen 80;
    server_name zerochat.top; # 换成你的域名
    # 强制跳转 HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name zerochat.top;

    ssl_certificate /etc/nginx/ssl/zerochat.top_bundle.pem; 
    ssl_certificate_key /etc/nginx/ssl/zerochat.top.key;

    ssl_session_timeout 1d;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        proxy_pass http://app:3000; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}