name: deploy zero-chat server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Serve
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./*, !.git"
          target: "/home/ubuntu/zero-chat"
          rm: false

      - name: Remote Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |

            if [ ! -d "/home/ubuntu/zero-chat" ]; then
              echo "目录 /home/ubuntu/zero-chat 不存在"
              exit 1
            fi

            cd /home/ubuntu/zero-chat > /dev/null 2>&1

            if [ $? -eq 0 ]; then
              echo "成功进入 /home/ubuntu/zero-chat"
            else
              echo "失败进入 /home/ubuntu/zero-chat"
              exit 1
            fi

            if [ ! -d "ssl" ]; then
              echo "SSL 证书文件夹丢失"
              exit 1
            fi

            if [ ! -f ".env" ]; then
              echo ".env 文件丢失！"
              exit 1
            fi

            if [ ! -f "Dockerfile" ]; then
              echo "根目录下缺少 Dockerfile,无法构建镜像"
              exit 1
            fi

            if sudo docker-compose up --build -d --force-recreate --remove-orphans; then
              echo "正在等待容器初始化..."
            else
              echo "Docker Compose 启动失败!"
              exit 1
            fi

            echo "正在修复文件换行格式 (CRLF to LF)..."
            sed -i 's/\r//g' .env
            sed -i 's/\r//g' init-db.sh
            bash init-db.sh

            echo "等待容器启动"
            sleep 15
            echo "检查容器状态"
            FAILED_CONTAINERS=$(sudo docker ps -a --filter "status=exited" --filter "status=restarting" --format "{{.Names}}")

            if [ -z "$FAILED_CONTAINERS" ]; then
              echo "所有容器已成功启动并保持运行！"
              sudo docker ps
              sudo find . -maxdepth 1 ! -name '.' ! -name '..' \
                ! -name '.env' \
                ! -name 'data' \
                ! -name 'ssl' \
                ! -name 'nginx' \
                ! -name 'certbot' \
                ! -name 'docker-compose.yml' \
                ! -name 'init-db.sh' \
                -exec rm -rf {} +
            else
              echo "部署失败以下容器启动后崩溃"
              echo "$FAILED_CONTAINERS"
              echo ">>> 正在打印最后20行错误日志"
              sudo docker-compose logs --tail=20
              exit 1
            fi
